[fresh]
primary   = "#62bac6"
secondary = "#eac786"
magenta   = "#c88bda"
red       = "#e27881"
orange    = "#e79c7e"
yellow    = "#eac786"
green     = "#98C379"
cyan      = "#62bac6"
blue      = "#71b9f4"
text      = "#E6E6E6"
subtext1  = "#C9CCD3"
subtext0  = "#ABB2BF"
overlay2  = "#969DAB"
overlay1  = "#818896"
overlay0  = "#6C7280"
surface2  = "#5B626D"
surface1  = "#4A505A"
surface0  = "#393E47"
base      = "#282C34"
mantle    = "#21252B"
crust     = "#1D1F23"

[classic]
primary   = "#61AFEF"
secondary = "#E6C07B"
magenta   = "#C678DD"
red       = "#E06C75"
orange    = "#E39678"
yellow    = "#E6C07B"
green     = "#98C379"
cyan      = "#56B6C2"
blue      = "#61AFEF"
text      = "#ABB2BF"
subtext1  = "#98a4b4"
subtext0  = "#8a95a4"
overlay2  = "#7c8694"
overlay1  = "#6e7784"
overlay0  = "#606874"
surface2  = "#525964"
surface1  = "#444a54"
surface0  = "#363b44"
base      = "#282C34"
mantle    = "#21252B"
crust     = "#1D1F23"





